name: be_better_u
description: "A flutter project for fitness"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: "^2.3.11"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/utils/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/iPhone.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter_native_splash:
  color: "#1A202C"
  image: "assets/splash.png"
  
  # Android settings
  android: true
  android_gravity: center
  
  # iOS settings
  ios: true
  ios_content_mode: center
  
  # Dark mode settings
  color_dark: "#000000"
  image_dark: "assets/splash.png"
  
  # Web settings
  web: true
  web_image_mode: center