// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmdrwhbTOu0a0l0cUuXU1IaiUg0ZzwaLM',
    appId: '1:840977980240:web:6f0ee2181038c7a1efea55',
    messagingSenderId: '840977980240',
    projectId: 'be-better-u',
    authDomain: 'be-better-u.firebaseapp.com',
    storageBucket: 'be-better-u.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlMZL-o3RklF89u4_rRHtanoQtMUjQB2A',
    appId: '1:840977980240:android:382e63eff752c7f3efea55',
    messagingSenderId: '840977980240',
    projectId: 'be-better-u',
    storageBucket: 'be-better-u.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFg2ivN4RWfAR7d-VlzJFbcigOHfsDzVk',
    appId: '1:840977980240:ios:1823a15174897d47efea55',
    messagingSenderId: '840977980240',
    projectId: 'be-better-u',
    storageBucket: 'be-better-u.firebasestorage.app',
    iosBundleId: 'com.example.beBetteru',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFg2ivN4RWfAR7d-VlzJFbcigOHfsDzVk',
    appId: '1:840977980240:ios:1823a15174897d47efea55',
    messagingSenderId: '840977980240',
    projectId: 'be-better-u',
    storageBucket: 'be-better-u.firebasestorage.app',
    iosBundleId: 'com.example.beBetteru',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmdrwhbTOu0a0l0cUuXU1IaiUg0ZzwaLM',
    appId: '1:840977980240:web:99f843935550ab79efea55',
    messagingSenderId: '840977980240',
    projectId: 'be-better-u',
    authDomain: 'be-better-u.firebaseapp.com',
    storageBucket: 'be-better-u.firebasestorage.app',
  );

}